#define _GNU_SOURCE

#include "libote_wrap.h"
#include "aux.h"
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <inttypes.h>
#include <math.h>
#include <sodium.h>
#include <pthread.h>
#include <time.h>

#include <netinet/in.h>
#include <netinet/tcp.h>
#include <arpa/inet.h>
#include <fcntl.h>
#include <signal.h>
#include <unistd.h>
#include <errno.h>
#include <sys/socket.h>
#include <sys/epoll.h>
#include <sys/types.h>
#include <sys/eventfd.h>
#define SPORT 8080
#define CPORT 8081
#define GCPORT 1212

#define MAX_EVENTS      512          //epoll events per call
#define MAX_CONNECTIONS 65536        //fd-indexed connection table size
#define RECV_BUF_SIZE   4096         //per-read stack buffer
#define BACKLOG         1024         //listen() backlog
#define SEND_BATCH_SIZE 256          //batch size for the htonl/ntohl conversion loop in send/recv

#define MAX_ARRAY_ELEMENTS 64ULL * 1024ULL * 1024ULL    //max no. elements that server will receive
static const bool local = true;                         //for development, set to true
static int          shutdown_requested = 0;
static time_t       shutdown_deadline  = 0;
static int          active_count       = 0;             //no. active client connections
#define GRACEFUL_TIMEOUT_SECS 1
 
#define THRESHOLD 2
static bool verbose, cout, light;
static uint32_t m, L, line, expon, FF_size = 17;  //n = number of records, m = number of attributes, L = bitlength per attribute, line = record bitlength
volatile int n = 0, nbytes;
double artificial_delay = 0., RTT = 0.05;   //these should become redundant
bool benchmarking = false;
const int rsize = 3;                        //how short the vector should be after recursive size-reduction in Couteau method
static int self_fd, s2_fd;
static int exchange_eventfd = -1;

static uint8_t *D;
static int D1_cols;
#define D1(r, c) D[(r) * D1_cols + (c)]     //emulate 2D static array (life is easier with 1D arrays)

//benchmarking...
double univ_start = 0, univ_end = 0, univ_final;

/*
 * Custom objects for networking.
 * Disclaimer: most of the networking code was (at least originally)
 * generated by AI (Claude), albeit closely supervised, since it is
 * a benign task with no novelty impact
 */

typedef enum {
    INTERSECT_FULL = 0,
    INTERSECT_MINUS,
} intersect_version_t;

typedef enum {
    CONN_FREE = 0,
    CONN_ACTIVE,
    CONN_CLOSING,
} conn_state_t;

typedef enum {
    PARSE_READING_HEADER = 0,   // waiting to accumulate 8 header bytes
    PARSE_READING_PAYLOAD,  // waiting to accumulate `count` payload bytes
} parse_state_t;

typedef struct write_chunk {
    uint8_t         *buf;
    size_t           len;
    size_t           off;       // how many bytes of this chunk already sent
    struct write_chunk *next;
} write_chunk_t;

typedef struct {
    parse_state_t state;

    // Header accumulation
    uint8_t  header_buf[8];
    size_t   header_got;    // how many header bytes received so far

    // Payload accumulation
    uint64_t count;         // decoded from header
    uint8_t *payload;       // malloc'd buffer
    size_t   payload_got;   // how many payload bytes received so far
} parser_t;

typedef struct {
    int fd;
    bool ret;
    conn_state_t conn_state;
    parse_state_t parse_state;

    parser_t parser;
    write_chunk_t *write_head;
    write_chunk_t *write_tail;
} connection_t;

typedef struct {
    int client_fd;
    uint8_t *arr;
    uint64_t count;
} query_thread_args;

typedef struct {
    int client_fd;
    uint8_t *response;
    uint64_t response_len;
} query_thread_result;

typedef struct result_node {
    query_thread_result   *result;
    struct result_node  *next;
} result_node_t;

typedef struct {
    result_node_t  *head;
    result_node_t  *tail;
} result_queue_t;

static result_queue_t result_queue = {NULL, NULL};
static pthread_mutex_t result_queue_mutex = PTHREAD_MUTEX_INITIALIZER;
static const intersect_version_t intersect_version = INTERSECT_FULL;

static connection_t conn_table[MAX_CONNECTIONS];
static int          epoll_fd  = -1;
static volatile int running   = 1;


static int send_8(int target_fd, uint8_t *arr, uint64_t count){
    if(send_uint8_array(target_fd, arr, count, SEND_BATCH_SIZE) != 0){
        fprintf(stderr, "send failed\n");
        return -1;
    }
    return 0;
}

static int send_32(int target_fd, uint32_t *arr, uint64_t count){
    if(send_uint32_array(target_fd, arr, count, SEND_BATCH_SIZE) != 0){
        fprintf(stderr, "send failed\n");
        return -1;
    }
    return 0;
}

static int receive_8(int target_fd, uint8_t **out_arr, uint64_t *out_count){
    uint8_t *arr;
    uint64_t count;
    int rc = recv_uint8_array(target_fd, &arr, &count, MAX_ARRAY_ELEMENTS);

    if(rc == -1){
        fprintf(stderr, "recv failed: syscall error: %s\n", strerror(errno));
        return -1;
    }
    else if(rc == -2){
        fprintf(stderr, "recv failed: server closed connection unexpectedly\n");
        return -1;
    }
    else if(rc < -2){
        fprintf(stderr, "recv failed: rc=%d, count = %" PRIu64 "\n", rc, count);
        return -1;
    }
    *out_arr = arr;
    *out_count = count;
    return 0;
}

static int receive_32(int target_fd, uint32_t **out_arr, uint64_t *out_count){
    uint32_t *arr;
    uint64_t count;
    int rc = recv_uint32_array(target_fd, &arr, &count, MAX_ARRAY_ELEMENTS);

    if(rc == -1){
        fprintf(stderr, "recv failed: syscall error: %s\n", strerror(errno));
        return -1;
    }
    else if(rc == -2){
        fprintf(stderr, "recv failed: server closed connection unexpectedly\n");
        return -1;
    }
    else if(rc < -2){
        fprintf(stderr, "recv failed: rc=%d\n", rc);
        return -1;
    }
    *out_arr = arr;
    *out_count = count;
    return 0;
}

static void enqueue_result(result_queue_t *q, query_thread_result *result){
    result_node_t *node = malloc(sizeof(result_node_t));
    node->result = result;
    node->next   = NULL;
    if (q->tail) {
        q->tail->next = node;
        q->tail       = node;
    } else {
        q->head = node;
        q->tail = node;
    }
}

static query_thread_result *dequeue_result(result_queue_t *q){
    if (!q->head){
        fprintf(stderr, "head not initialised\n");
        return NULL;
    }
    result_node_t *node = q->head;
    query_thread_result *result = node->result;
    q->head = node->next;
    if (!q->head)
        q->tail = NULL;
    free(node);
    return result;
}

/* Make a file descriptor non-blocking. */
static int set_nonblocking(int fd){
    int flags = fcntl(fd, F_GETFL, 0);
    if (flags == -1) return -1;
    return fcntl(fd, F_SETFL, flags | O_NONBLOCK);
}

static void on_signal(int sig){
    (void)sig;
    if (shutdown_requested) {
        // Second signal — give up and exit immediately
        running = 0;
        return;
    }
    shutdown_requested = 1;
    shutdown_deadline  = time(NULL) + GRACEFUL_TIMEOUT_SECS;
}
/* Register fd with epoll (edge-triggered, readable + writable). */
static int epoll_add(int fd, uint32_t events){
    struct epoll_event ev = {
        .events  = events,
        .data.fd = fd,
    };
    return epoll_ctl(epoll_fd, EPOLL_CTL_ADD, fd, &ev);
}

/* Modify an existing epoll registration. */
static int epoll_mod(int fd, uint32_t events){
    struct epoll_event ev = {
        .events  = events,
        .data.fd = fd,
    };
    return epoll_ctl(epoll_fd, EPOLL_CTL_MOD, fd, &ev);
}

static void connection_close(int fd){
    active_count--;
    if (fd < 0 || fd >= MAX_CONNECTIONS) return;

    connection_t *c = &conn_table[fd];
    if (c->conn_state == CONN_FREE) return;

    printf("Connection closed: fd=%d\n", fd);

    epoll_ctl(epoll_fd, EPOLL_CTL_DEL, fd, NULL);
    close(fd);

    /* Free any per-connection resources here. */
    memset(c, 0, sizeof(*c));
    c->conn_state = CONN_FREE;
    if(c->parser.payload != NULL) free(c->parser.payload);    //<--
    write_chunk_t *chunk = c->write_head;

    while (chunk) {
        write_chunk_t *next = chunk->next;
        free(chunk->buf);
        free(chunk);
        chunk = next;
    }
    c->write_head = NULL;
    c->write_tail = NULL;
}

static void servers_communicate(){
    artificial_delay += RTT;
}

static int s2_connect(){
    struct sockaddr_in address;
    int opt = 1;
    int sendbuf = 4 * 1024 * 1024;
    int recvbuf = 4 * 1024 * 1024;
    socklen_t addrlen = sizeof(address);

    // Creating socket file descriptor
    if((self_fd = socket(AF_INET, SOCK_STREAM, 0)) < 0) {
        perror("socket failed");
        return -1;
    }

    // Forcefully attaching socket to the port 8080
    if(setsockopt(self_fd, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt))){
        perror("setsockopt");
        return -1;
    }
    if(setsockopt(self_fd, SOL_SOCKET, SO_REUSEPORT, &opt, sizeof(opt))){
        perror("setsockopt");
        return -1;
    }
    if(setsockopt(self_fd, SOL_SOCKET, SO_SNDBUF, &sendbuf, sizeof(sendbuf))){
        perror("setsockopt");
        return -1;
    }
    if(setsockopt(self_fd, SOL_SOCKET, SO_RCVBUF, &recvbuf, sizeof(recvbuf))){
        perror("setsockopt");
        return -1;
    }

    address.sin_family = AF_INET;
    address.sin_addr.s_addr = INADDR_ANY;
    address.sin_port = htons(SPORT);

    if(bind(self_fd, (struct sockaddr*)&address, sizeof(address)) < 0){
        perror("bind failed");
        return -1;
    }
    if(listen(self_fd, 3) < 0){
        perror("listen");
        return -1;
    }
    fprintf(stderr, "waiting for connection to s2...\n");
    if ((s2_fd = accept(self_fd, (struct sockaddr*)&address, &addrlen)) < 0){
        perror("accept");
        return -1;
    }
    fprintf(stderr, "Connected to s2\n");
    return s2_fd;
}

/*
 * send system parameters to server2 following connection
 */
static int s2_hello(){
    int buf_size = 8;
    uint32_t helloBuf[buf_size];
    helloBuf[0] = n;
    helloBuf[1] = m;
    helloBuf[2] = L;
    helloBuf[3] = verbose;
    helloBuf[4] = cout;
    helloBuf[5] = light;
    helloBuf[6] = FF_size;
    helloBuf[7] = THRESHOLD;
    if(send_32(s2_fd, helloBuf, buf_size) != 0)
        return -1;
    printf("Finished server_hello\n");
    return 0;
}

static int create_listen_socket(uint16_t port){
    int fd = socket(AF_INET, SOCK_STREAM | SOCK_NONBLOCK | SOCK_CLOEXEC, 0);
    if (fd == -1) { perror("socket"); return -1; }

    /* Allow quick restart after crash (avoids TIME_WAIT bind errors). */
    int opt = 1;
    setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt));
    setsockopt(fd, SOL_SOCKET, SO_REUSEPORT, &opt, sizeof(opt));

    struct sockaddr_in addr = {
        .sin_family      = AF_INET,
        .sin_addr.s_addr = INADDR_ANY,
        .sin_port        = htons(port),
    };

    if (bind(fd, (struct sockaddr *)&addr, sizeof(addr)) == -1) {
        perror("bind"); close(fd); return -1;
    }
    if (listen(fd, BACKLOG) == -1) {
        perror("listen"); close(fd); return -1;
    }

    return fd;
}

/*
 * Print records for up to 100 clients.
 * FOR DEVELOPMENT ONLY - reveals all client values
 */
static int print_records(){
    if(n > 100) return 1;
    uint8_t (*D2)[nbytes] = NULL;
    uint8_t *recv_arr;
    uint64_t count, exp_count = nbytes * line;

    if(receive_8(s2_fd, &recv_arr, &count) == 0 && count == exp_count)
        D2 = (void *)recv_arr;
    else{
        fprintf(stderr, "receive D2 from s2 failed, no. elements received = %" PRIu64 "\n", count);
        return -1;
    }
    uint8_t D1_send[line][nbytes];
    for(int i = 0; i < line; i++)
        memcpy(&D1_send[i], &D1(i, 0), nbytes);

    if(send_8(s2_fd, (uint8_t*)D1_send, exp_count) != 0)
        return -1;

   bool d;
    for(int i = 0; i < n; i++){
        for(int j = 0; j < line; j++){
            d = (D1(j, i/8) >> i%8 & 1)  ^ (D2[j][i/8] >> i%8 & 1);
            if(j == 0 && j == line - 1)
                printf("(%d)\n", d);
            else if(j == 0 && j % L == L - 1)
                printf("(%d|", d);
            else if(j == 0)
                printf("(%d", d);
            else if(j == line - 1)
                printf("%d)\n", d);
            else if(j % L == L - 1)
                printf("%d|", d);
            else printf("%d", d);
        }
    }
    printf("\n");
    free(D2);
    return 0;
}

/*
 * Main method for computing intersection count. Performs distributed AND on all records.
 * Input: Server 1's dataset (global variable D), or alternatively alt_D, used for
 * CouteauHybrid only (alt_D is the output of the size reduction protocol from Couteau)
 * Output:
*D_i is each server's boolean share of the record data, I_i is the computed intersection shares
*/
static int intersectminus(int n_fixed, int l, int L, int no_multis_bytes, uint8_t (*alt_D)[tobytes(n_fixed)], uint8_t (*T1)[no_multis_bytes], uint8_t **Z1, int *intersect_indices, bool *t){
    int nbytes_fixed = tobytes(n_fixed);
    int lhalf = l - (l / 2);
    int initsize = lhalf * nbytes_fixed * sizeof(uint8_t);
    int de_size = (l / 2) * nbytes_fixed * sizeof(uint8_t);
    uint8_t (*I1)[nbytes_fixed] = malloc(initsize);
    if(!I1){
        fprintf(stderr, "could not allocate I1\n");
        return -1;
    }

    uint8_t (*d1)[nbytes_fixed] = malloc(de_size), (*e1)[nbytes_fixed] = malloc(de_size);
    uint8_t (*d2)[nbytes_fixed] = NULL, (*e2)[nbytes_fixed] = NULL; // should get malloc'ed by recv()
    uint8_t (*d)[nbytes_fixed] = NULL, (*e)[nbytes_fixed] = NULL; // will reuse from d2 and e2
    if(!d1 || !e1){
        fprintf(stderr, "could not allocate d or e arrays\n");
        return -1;
    }

    int index1, index2;
    int index_len = l / L;
    int no_pairs = l / 2; //e.g. if we have 7 indices, we have 3 pairs and 1 leftover
    bool uneven = no_pairs * 2 != l;
    l -= no_pairs;

    int index = 0, subindex = 0, j = 0;
    for(int pair = 0; pair < no_pairs; pair++){
        for(int i = 0; i < nbytes_fixed; i++){
            index1 = intersect_indices[index] * L + subindex;
            index2 = subindex + 1 == L? intersect_indices[index + 1] * L: index1 + 1;
            if(alt_D){
                //printf("using altD\n");
                //server 1 computes intermediate values d1 = x1 - a1
                d1[pair][i] = alt_D[index1][i] ^ (255 * t[index * L + subindex]) ^ T1[0][j];
                //e1 = y1 - b1
                e1[pair][i] = alt_D[index2][i] ^ (255 * t[index * L + subindex + 1]) ^ T1[1][j++];
            }
            else{
                d1[pair][i] = D1(index1, i) ^ (255 * t[index * L + subindex]) ^ T1[0][j];
                e1[pair][i] = D1(index2, i) ^ (255 * t[index * L + subindex + 1]) ^ T1[1][j++];
            }
        }
        subindex++;
        if(subindex == L){
            subindex -= L;
            index++;
        }
        subindex++;
        if(subindex == L){
            subindex -= L;
            index++;
        }
    }

    uint8_t *recv_arr;
    uint64_t count;
    if(send_8(s2_fd, (uint8_t *)d1, de_size) != 0){
        fprintf(stderr, "send d1 to s2 failed\n");
        return -1;
    }
    if(receive_8(s2_fd, &recv_arr, &count) == 0 && count == de_size){
        d2 = (void *)recv_arr;
        d = d2;
    }
    else{
        fprintf(stderr, "receive d2 from s2 failed\n");
        return -1;
    }

    if(send_8(s2_fd, (uint8_t *)e1, de_size) != 0){
        fprintf(stderr, "send e1 to s2 failed\n");
        return -1;
    }

    if(receive_8(s2_fd, &recv_arr, &count) == 0 && count == de_size){
        e2 = (void *)recv_arr;
        e = e2;
    }
    else{
        fprintf(stderr, "receive e2 from s2 failed\n");
        return -1;
    }
    j = 0;
    for(int pair = 0; pair < no_pairs; pair++){
        for(int i = 0; i < nbytes_fixed; i++){
            //now we assume both servers have all parts to reconstruct d and e, and thus both calculate:
            // --------------------
            d[pair][i] = d1[pair][i] ^ d2[pair][i];
            e[pair][i] = e1[pair][i] ^ e2[pair][i];
            //server 1 computes z1 as d*b1 + e*a1 + c1
            I1[pair][i] = (d[pair][i] & T1[1][j]) ^ (e[pair][i] & T1[0][j]) ^ T1[2][j];
            j++;
        }
    }

    free(d2);
    free(e2);

    if(uneven){
        int leftoverindex = (intersect_indices[index_len - 1] + 1) * L - 1;
        for(int i = 0; i < nbytes_fixed; i++){
            if(alt_D){
                //printf("using altD\n");
                I1[no_pairs][i] = alt_D[leftoverindex][i] ^ (255 * t[index * L + subindex]); }
            else I1[no_pairs][i] = D1(leftoverindex, i) ^ (255 * t[index * L + subindex]);
        }
    }

    int jcheckpoint, spacing;
    int no_rounds = (int)ceil(log2(l));
    for(int round = 0; round < no_rounds; round++){
        no_pairs = l / 2; //e.g. if we have 7 indices, we have 3 pairs and 1 leftover
        l -= no_pairs;
        spacing = (int)pow(2, round);
        jcheckpoint = j;
        for(int pair = 0; pair < no_pairs; pair++){
            index1 = 2*pair*spacing; //first index of the pair
            index2 = spacing*(2*pair + 1); //second index of the pair=
            for(int i = 0; i < nbytes_fixed; i++){
                d1[pair][i] = I1[index1][i] ^ T1[0][j];
                e1[pair][i] = I1[index2][i] ^ T1[1][j++];
            }
        }
        j = jcheckpoint;
        int sendsize = no_pairs * nbytes_fixed;
        if(send_8(s2_fd, (uint8_t *)d1, sendsize) != 0){
            fprintf(stderr, "send d1 to s2 failed\n");
            return -1;
        }
        if(receive_8(s2_fd, &recv_arr, &count) == 0 && count == sendsize){
            d2 = (void *)recv_arr;
            d = d2;
        }
        else{
            fprintf(stderr, "receive d2 from s2 failed\n");
            return -1;
        }

        if(send_8(s2_fd, (uint8_t *)e1, sendsize) != 0){
            fprintf(stderr, "send e1 to s2 failed\n");
            return -1;
        }

        if(receive_8(s2_fd, &recv_arr, &count) == 0 && count == sendsize){
            e2 = (void *)recv_arr;
            e = e2;
        }
        else{
            fprintf(stderr, "receive d2 from s2 failed\n");
            return -1;
        }

        //servers publish shares, i.e. server 1 sends D1 and E1, server 2 similarly
        for(int pair = 0; pair < no_pairs; pair++){
            index1 = 2*pair*spacing;
            for(int i = 0; i < nbytes_fixed; i++){
                //now both servers have all parts to reconstruct D and E, and thus both calculate:
                d[pair][i] = d1[pair][i] ^ d2[pair][i];
                e[pair][i] = e1[pair][i] ^ e2[pair][i];
                //server 1 computes z1 as d*b1 + e*a1 + c1
                I1[index1][i] = (d[pair][i] & T1[1][j]) ^ (e[pair][i] & T1[0][j]) ^ T1[2][j];
                j++;
            }
        }
        free(d2);
        free(e2);
    }

    *Z1 = realloc(I1, nbytes_fixed);
    if(!Z1){
        fprintf(stderr, "error reallocating Z1\n");
        return -1;
    }
    free(d1);
    free(e1);
    return 0;
}

int intersectfull(int n_fixed, int no_multis_bytes, uint8_t (*T1)[no_multis_bytes], uint8_t **Z1, bool *q, bool *t){
    int nbytes_fixed = tobytes(n_fixed);
    int l = L;  //l is now the length of each subvector
    int lhalf = l - (l / 2);
    int initsize = lhalf * m * nbytes_fixed * sizeof(uint8_t);
    uint8_t (*I1)[lhalf][nbytes_fixed] = malloc(initsize);
    if(!I1){
        fprintf(stderr, "could not allocate I1\n");
        return -1;
    }

    for(int i = 0; i < m; i++)
        printf("q -> %d\n", q[i]);
    printf("\n");
    for(int i = 0; i < L * m; i++)
        printf("t -> %d\n", t[i]);
    printf("\n");

    uint8_t (*d1)[m][nbytes_fixed] = malloc(initsize), (*e1)[m][nbytes_fixed] = malloc(initsize);
    uint8_t (*d2)[m][nbytes_fixed] = NULL, (*e2)[m][nbytes_fixed] = NULL;
    uint8_t (*d)[m][nbytes_fixed] = NULL, (*e)[m][nbytes_fixed] = NULL;
    if(!d1 || !e1){
        fprintf(stderr, "could not allocate d or e arrays\n");
        return -1;
    }

    int index1, index2;
    int no_pairs = l / 2;
    bool uneven = no_pairs * 2 != l;
    l -= no_pairs;

    int index = 0, subindex = 0, j = 0;
    for(int attribute = 0; attribute < m; attribute++){
        for(int pair = 0; pair < no_pairs; pair++){
            for(int i = 0; i < nbytes_fixed; i++){
                index1 = attribute * L + (pair * 2);
                index2 = index1 + 1;
                d1[pair][attribute][i] = D1(index1, i) ^ (255 * t[index1]) ^ T1[0][j];
                e1[pair][attribute][i] = D1(index2, i) ^ (255 * t[index2]) ^ T1[1][j++];
            }
        }
    }

    uint8_t *recv_arr;
    uint64_t count;
    if(send_8(s2_fd, (uint8_t *)d1, initsize) != 0){
        fprintf(stderr, "send d1 to s2 failed\n");
        return -1;
    }
    if(receive_8(s2_fd, &recv_arr, &count) == 0 && count == initsize){
        d2 = (void *)recv_arr;
        d = d2;
    }
    else{
        fprintf(stderr, "receive d2 from s2 failed\n");
        return -1;
    }

    if(send_8(s2_fd, (uint8_t *)e1, initsize) != 0){
        fprintf(stderr, "send e1 to s2 failed\n");
        return -1;
    }

    if(receive_8(s2_fd, &recv_arr, &count) == 0 && count == initsize){
        e2 = (void *)recv_arr;
        e = e2;
    }
    else{
        fprintf(stderr, "receive e2 from s2 failed\n");
        return -1;
    }

    j = 0;
    for(int attribute = 0; attribute < m; attribute++){
        for(int pair = 0; pair < no_pairs; pair++){
            for(int i = 0; i < nbytes_fixed; i++){
                d[pair][attribute][i] = d1[pair][attribute][i] ^ d2[pair][attribute][i];
                e[pair][attribute][i] = e1[pair][attribute][i] ^ e2[pair][attribute][i];
                I1[pair][attribute][i] = (d[pair][attribute][i] & T1[1][j]) ^ (e[pair][attribute][i] & T1[0][j]) ^ T1[2][j];
                j++;
            }
        }
    }
    free(d2);
    free(e2);

    int leftoverindex;
    if(uneven){
        for(int attribute = 0; attribute < m; attribute++){
            for(int i = 0; i < nbytes_fixed; i++){
                leftoverindex = L * (attribute + 1) - 1;
                I1[no_pairs][attribute][i] = D1(leftoverindex, i) ^ (255 * t[leftoverindex]);
            }
        }
    }

    int jcheckpoint, spacing;
    int no_rounds = (int)ceil(log2(l));
    for(int round = 0; round < no_rounds; round++){
        l -= no_pairs;
        spacing = (int)pow(2, round);
        jcheckpoint = j;
        for(int attribute = 0; attribute < m; attribute++){
            for(int pair = 0; pair < no_pairs; pair++){
                index1 = 2*pair*spacing;
                index2 = spacing*(2*pair + 1);
                for(int i = 0; i < nbytes_fixed; i++){
                    d1[pair][attribute][i] = I1[index1][attribute][i] ^ T1[0][j];
                    e1[pair][attribute][i] = I1[index2][attribute][i] ^ T1[1][j++];
                }
            }
        }
        j = jcheckpoint;
        int sendsize = l * m * nbytes_fixed;
        if(send_8(s2_fd, (uint8_t *)d1, sendsize) != 0){
            fprintf(stderr, "send d1 to s2 failed\n");
            return -1;
        }
        if(receive_8(s2_fd, &recv_arr, &count) == 0 && count == sendsize){
            d2 = (void *)recv_arr;
            d = d2;
        }
        else{
            fprintf(stderr, "receive d2 from s2 failed\n");
            return -1;
        }

        if(send_8(s2_fd, (uint8_t *)e1, sendsize) != 0){
            fprintf(stderr, "send e1 to s2 failed\n");
            return -1;
        }

        if(receive_8(s2_fd, &recv_arr, &count) == 0 && count == sendsize){
            e2 = (void *)recv_arr;
            e = e2;
        }
        else{
            fprintf(stderr, "receive d2 from s2 failed\n");
            return -1;
        }

        //servers publish shares, i.e. server 1 sends D1 and E1, server 2 similarly
        for(int attribute = 0; attribute < m; attribute++){
            for(int pair = 0; pair < no_pairs; pair++){
                index1 = 2*pair*spacing;
                for(int i = 0; i < nbytes_fixed; i++){
                    //now both servers have all parts to reconstruct D and E, and thus both calculate:
                    d[pair][attribute][i] = d1[pair][attribute][i] ^ d2[pair][attribute][i];
                    e[pair][attribute][i] = e1[pair][attribute][i] ^ e2[pair][attribute][i];
                    //server 1 computes z1 as d*b1 + e*a1 + c1
                    I1[index1][attribute][i] = (d[pair][attribute][i] & T1[1][j]) ^ (e[pair][attribute][i] & T1[0][j]) ^ T1[2][j];
                    j++;
                }
            }
        }
        free(d2);
        free(e2);
    }

    free(d1);
    free(e1);

    //z is intermediate results, Z is final
    uint8_t (*z1)[nbytes_fixed] = malloc(m * nbytes_fixed * sizeof(uint8_t));
    for(int attribute = 0; attribute < m; attribute++)
        memcpy(z1[attribute], I1[0][attribute], nbytes_fixed);
    free(I1);

    for(int attribute = 0; attribute < m; attribute++)
        for(int i = 0; i < nbytes_fixed; i++)
            z1[attribute][i] ^= 255 * q[attribute];            //s2 needs to negate

    for(int i = 0; i < m; i++)
        printf("z -> %d\n", z1[i][0] >> 0 & 1);
    printf("\n");

    int intersect_indices[1];
    intersect_indices[0] = 0;//set intersect_indices to 'all'
    for(int attribute = 0; attribute < m; attribute++)
        t[attribute] = 0;

    no_multis_bytes = (m - 1) * nbytes_fixed;
    uint8_t (*T1_2)[no_multis_bytes] = malloc(3 * no_multis_bytes * sizeof(uint8_t));
    for(int k = 0; k < 3; k++)  //tedious necessary rearrangement of triples
        memcpy(T1_2[k], &T1[k][j], no_multis_bytes);

    int ret = intersectminus(n_fixed, m, m, no_multis_bytes, z1, T1_2, Z1, intersect_indices, t);
    printf("printing Z:\n");
    printboolvec(*Z1, n_fixed);
    free(z1);
    free(T1_2);
    return ret;
}

static void cout_size_reduction(int batch_bytes, int max_depth, uint8_t (*R)[batch_bytes * 8], uint32_t (*A)[batch_bytes * 8], uint32_t *msgs1, uint32_t *msgs2, int *js, int *js_acc){
    int batch_size = batch_bytes * 8;

    //server1
    int c = 0;
    int noOTs_j = js_acc[max_depth];
    randombytes_buf((uint8_t*)R, noOTs_j * batch_bytes);
    
    bool b;
    uint32_t a;
    int byte = 0, bit = 0;
    for(int depth = 0; depth < max_depth; depth++){
        random_vector(A[js_acc[depth]], js[depth] * batch_size, js[depth] + 1);
        for(int j = 0; j < js[depth]; j++){
            byte = 0, bit = 0;
            for(int i = 0; i < batch_size; i++){
                if(bit > 7){
                    bit = 0;
                    byte++;
                }
                b = R[js_acc[depth] + j][byte] >> bit++ & 1;
                a = A[js_acc[depth] + j][i];
                msgs1[c] = FF_convert(b - a, js[depth] + 1);
                msgs2[c++] = FF_convert(1 - a - b, js[depth] + 1);
            }
        }
    }
    if(verbose) printf("finished cout_size_reduction()\n");
}

static void cout_product_sharing(int batch_bytes, uint8_t (*r)[batch_bytes], uint8_t (*a)[batch_bytes], uint8_t **msgs1, uint8_t *msgs2, int noOTs_bytes){
    
    //server1
    int c = 0;
    randombytes_buf((uint8_t*)r, noOTs_bytes);
    randombytes_buf((uint8_t*)a, noOTs_bytes);

    *msgs1 = (uint8_t*)a;
    
    for(int i = 0; i < batch_bytes; i++)
        for(int j = 0; j < expon; j++)
            msgs2[c++] = a[j][i] ^ r[j][i];
    if(verbose) printf("finished cout_product_sharing()\n");
}

static int couteauPrepSR(int batch_bytes, int max_depth, uint8_t (*R)[batch_bytes], uint32_t (*A)[batch_bytes * 8], int *js, int *js_acc){
    
    if(js[0] < 2)
        return 0;
    
    int batch_size = batch_bytes * 8;

    int noOTs_j = js_acc[max_depth];
    int noOTs_SR = noOTs_j * batch_size, noOTs_SR_bytes = noOTs_j * batch_bytes;

    if(max_depth < 1)
        return -1;
    
    printf("noOTs_SR = %d\n", noOTs_SR);
    uint32_t *msgs1_SR = malloc(noOTs_SR * sizeof(uint32_t)), *msgs2_SR = malloc(noOTs_SR * sizeof(uint32_t));
    if(!msgs1_SR || !msgs2_SR){
        printf("error allocating msgs1 or msgs2\n");
        return -1;
    }
    
    cout_size_reduction(batch_bytes, max_depth, R, A, msgs1_SR, msgs2_SR, js, js_acc);
    OTeSend32(msgs1_SR, msgs2_SR, noOTs_SR);

    free(msgs1_SR);
    free(msgs2_SR);
    if(verbose) printf("finished couteauPrepSR()\n");
    return 0;
}

static int couteauPrepPS(int batch_bytes, uint8_t (*r)[batch_bytes], uint8_t (*a)[batch_bytes]){

    int batch_size = batch_bytes * 8;
    int noOTs_PS = expon * batch_size, noOTs_PS_bytes = expon * batch_bytes;
    uint8_t *msgs1_PS = NULL, *msgs2_PS = malloc(noOTs_PS_bytes * sizeof(uint8_t));

    if(!msgs2_PS){
        printf("error allocating msgs2\n");
        return -1;
    }

    cout_product_sharing(batch_bytes, r, a, &msgs1_PS, msgs2_PS, noOTs_PS_bytes);
    OTeSend1(msgs1_PS, msgs2_PS, noOTs_PS);

    free(msgs2_PS);
    if(verbose) printf("finished couteauPrepPS()\n");
    return 0;
}

static int couteauPrep(int batch_bytes, int max_depth, uint8_t (*R)[batch_bytes], uint32_t (*A)[batch_bytes * 8], uint8_t (*r)[batch_bytes], uint8_t (*a)[batch_bytes], int *js, int *js_acc){
    if(js[0] < 2){
        printf("skipping couteauPrep()\n");
        return 0;
    }

    if(max_depth > 0){  // if (need to do size reduction)
        if(couteauPrepSR(batch_bytes, max_depth, R, A, js, js_acc) == -1){
            fprintf(stderr, "failure in couteauPrepSR()\n");
            return -1;
        }
    } else{ printf("skipping size_reduction\n"); R = NULL, A = NULL; }

    if(couteauPrepPS(batch_bytes, r, a) == -1){
        fprintf(stderr, "failure in couteauPrepPS()\n");
        return -1;
    }

    if(verbose) printf("finished couteauPrep()\n");
    return 0;
}

static int couteauHybridPrep(int batch_bytes, int max_depth, uint8_t (*R)[batch_bytes], uint32_t (*A)[batch_bytes * 8], int *js, int *js_acc){
    if(js[0] < 2){
        printf("skipping couteauHybridPrep()\n");
        return 0;
    }

    if(max_depth > 0){  // if (need to do size reduction)
        if(couteauPrepSR(batch_bytes, max_depth, R, A, js, js_acc) == -1){
            fprintf(stderr, "failure in couteauPrepSR()\n");
            return -1;
        }
    } else{ printf("skipping size_reduction\n"); R = NULL, A = NULL; }

    if(verbose) printf("finished couteauHybridPrep()\n");
    return 0;
}

static int couteauSR(int n_fixed, int max_depth, uint8_t (**XS)[tobytes(n_fixed)], uint8_t (*R)[tobytes(n_fixed)], uint32_t (*A)[n_fixed], int *intersect_indices, bool *t, int *js, int *js_acc){
    
    int l = js[0];
    int nbytes_fixed = tobytes(n_fixed);
    int noOTs_j = js_acc[max_depth];
    uint8_t (*xs)[nbytes_fixed] = malloc(nbytes_fixed * (noOTs_j + rsize));
    memset(xs, 0, nbytes_fixed * (noOTs_j + rsize));
    
    if(!xs){
        printf("could not allocate xs\n");
        return -1;
    }
    
    int indexlen = l / L;
    int acc;

    //server1 sets x1 = x for every record
    for(int i = 0; i < nbytes_fixed; i++)
        for(int j = 0; j < indexlen; j++)
            for(int k = 0; k < L; k++)
                xs[j * L + k][i] = D1(intersect_indices[j] * L + k, i) ^ (255 * t[j * L + k]);

    if(l == 1 || max_depth == 0){
        *XS = realloc(xs, rsize * nbytes_fixed);
        printf("skipping size reduction\n");
        return 0;
    }
    for(int depth = 0; depth < max_depth; depth++){
        int arr_size = nbytes_fixed * js[depth];
        uint8_t (*z1)[nbytes_fixed] = malloc(arr_size), (*z2)[nbytes_fixed] = NULL, (*z)[nbytes_fixed] = z2; //reuse z2 array
        if(!z1){
            printf("could not allocate z1\n");
            return -1;
        }
        //server1 sends for each record: z1 = r[i] ^ x[i];
        for(int i = 0; i < nbytes_fixed; i++)
            for(int j = 0; j < js[depth]; j++)
                z1[j][i] = R[js_acc[depth] + j][i] ^ xs[js_acc[depth] + j][i];
        
        //servers exchange z1 and z2
        uint8_t *recv_arr;
        uint64_t count;
        if(send_8(s2_fd, (uint8_t *)z1, arr_size) != 0){
            fprintf(stderr, "send z1 to s2 failed\n");
            return -1;
        }
        if(receive_8(s2_fd, &recv_arr, &count) == 0 && count == arr_size)
            z2 = (void *)recv_arr;
        else{
            fprintf(stderr, "receive z2 from s2 failed\n");
            return -1;
        }

        //and calculate z as z = z1 ^ z2
        for(int i = 0; i < nbytes_fixed; i++)
            for(int j = 0; j < js[depth]; j++)
                z[j][i] = z1[j][i] ^ z2[j][i];
        
        //server1 calculates what will become xs[i+1]
        int byte = 0, bit = 0;
        for(int i = 0; i < n_fixed; i++){
            if(bit > 7){
                bit = 0;
                byte++;
            }
            acc = 0;
            for(int j = 0; j < js[depth]; j++){
                acc += (int)pow(-1, (z[j][byte] >> bit & 1)) * A[js_acc[depth] + j][i];
            }
            acc = FF_convert(-acc, js[depth] + 1);
            for(int j = 0; j < js[depth + 1]; j++)
                xs[js_acc[depth + 1] + j][byte] += (acc >> j & 1) << bit;
            bit++;
        }
        free(z1);
        free(z2);
    }
    *XS = &xs[js_acc[max_depth]];
    XS = realloc(xs, rsize * nbytes_fixed);
    if(verbose) printf("finished couteauSR()\n");
    return 0;
}

static int couteauPS(int n_fixed, int max_depth, uint8_t **Z1, uint8_t (*XS)[tobytes(n_fixed)], uint8_t (*r)[tobytes(n_fixed)], uint8_t (*a)[tobytes(n_fixed)]){


    int nbytes_fixed = tobytes(n_fixed);
    bool I[expon][rsize];
    powset(rsize, I, expon);
    //server1

    *Z1 = malloc(nbytes_fixed * sizeof(uint8_t));
    if(!Z1){
        printf("could not allocate Z1\n");
        return -1;
    }

    uint8_t *alpha = malloc(nbytes_fixed), *beta = NULL,
    (*Alpha)[nbytes_fixed] = malloc(nbytes_fixed * expon * sizeof(uint8_t)), (*Beta)[nbytes_fixed] = NULL,
    (*EX)[nbytes_fixed] = malloc(nbytes_fixed * expon * sizeof(uint8_t));
    if(!alpha || !Alpha || !EX){
        printf("could not allocate alpha, Alpha or EX\n");
        return -1;
    }

    uint8_t acc1;
    for(int i = 0; i < nbytes_fixed; i++){
        for(int k = 0; k < expon; k++){
            acc1 = 255;
            for(int j = 0; j < rsize; j++){
                if(I[k][j])
                    acc1 &= 255 ^ XS[j][i];
            }
            EX[k][i] = acc1;
            Alpha[k][i] = r[k][i] ^ acc1;
        }
    }
    randombytes_buf(alpha, nbytes_fixed);

    //servers send each other alpha and beta (+Alpha and Beta)
    uint8_t *recv_arr;
    uint64_t count;
    if(send_8(s2_fd, (uint8_t *)alpha, nbytes_fixed) != 0){
        fprintf(stderr, "send alpha to s2 failed\n");
        return -1;
    }
    if(receive_8(s2_fd, &recv_arr, &count) == 0 && count == nbytes_fixed)
        beta = (void *)recv_arr;
    else{
        fprintf(stderr, "receive beta from s2 failed\n");
        return -1;
    }

    if(send_8(s2_fd, (uint8_t *)Alpha, nbytes_fixed * expon) != 0){
        fprintf(stderr, "send Alpha to s2 failed\n");
        return -1;
    }
    if(receive_8(s2_fd, &recv_arr, &count) == 0 && count == nbytes_fixed * expon)
        Beta = (void *)recv_arr;
    else{
        fprintf(stderr, "receive Beta from s2 failed\n");
        return -1;
    }

    //server1
    uint8_t acc2;
    for(int i = 0; i < nbytes_fixed; i++){
        acc1 = 0;
        acc2 = 255;
        for(int k = 0; k < expon; k++)
            acc1 ^= a[k][i] ^ (Beta[k][i] & EX[k][i]);
        for(int j = 0; j < rsize; j++)
            acc2 &= 255 ^ XS[j][i];
        *Z1[i] = acc1 ^ acc2 ^ alpha[i] ^ beta[i];
    }

    free(XS);
    free(alpha);
    free(beta);
    free(Alpha);
    free(Beta);
    if(verbose) printf("finished couteauPS()\n");
    return 0;
}

static int couteauHybridET(int n_fixed, int max_depth, uint8_t **Z1, uint8_t (*R)[tobytes(n_fixed)], uint32_t (*A)[n_fixed], int no_multis_bytes, uint8_t (*T1)[no_multis_bytes], int *intersect_indices, bool *t, int *js, int *js_acc){
    if(js[0] < 1)
        return -1;
    int nbytes_fixed = tobytes(n_fixed);
    uint8_t (*XS)[nbytes_fixed] = NULL;
    couteauSR(n_fixed, max_depth, &XS, R, A, intersect_indices, t, js, js_acc);

    intersect_indices[0] = 0;
    for(int i = 0; i < rsize; i++)
        t[i] = 0;

    int ret = intersectminus(n_fixed, rsize, rsize, no_multis_bytes, XS, T1, Z1, intersect_indices, t);
    free(XS);
    if(verbose) printf("finished couteauHybridET()\n");
    return ret;
}

static int couteauET(int n_fixed, int max_depth, uint8_t **Z1, uint8_t (*R)[tobytes(n_fixed)], uint32_t (*A)[n_fixed], uint8_t (*r)[tobytes(n_fixed)], uint8_t (*a)[tobytes(n_fixed)], int *intersect_indices, bool *t, int *js, int *js_acc){
    if(js[0] < 1)
        return -1;
    
    int nbytes_fixed = tobytes(n_fixed);
    uint8_t (*XS)[nbytes_fixed] = NULL;

    // if (need to do size reduction)
    if(couteauSR(n_fixed, max_depth, &XS, R, A, intersect_indices, t, js, js_acc) == -1){
        fprintf(stderr, "failure in couteauSR\n");
        return -1;
    }

    if(couteauPS(n_fixed, max_depth, Z1, XS, r, a) == -1){
        fprintf(stderr, "failure in couteauPS\n");
        return -1;
    }

    if(verbose) printf("finished couteauET()\n");

    return 0;
}

//generate random records where no attribute is the vector of all 1s
static void generate_records(){
    //randombytes_buf(D, nbytes * line);
    memset(D, 0, nbytes * line);
    uint32_t r_vec[m][n];

    /*generate ints off of which to base the generated records.
    The vector of all 1s is omitted by setting FF = 2^L - 1 (instead of 2^L)*/
    random_vector((uint32_t*)r_vec, m * n, (1 << L) - 1);

    for(int attribute = 0; attribute < m; attribute++){
        for(int i = 0; i < n; i++){
            bool temp[L];
            int_to_vector((int)r_vec[attribute][i], temp, L);
            for(int k = 0; k < L; k++)
                D1(attribute * L + k, i/8) |= temp[k] << i%8;
        }
    }
}

//dabitgen algorithm according to [1] but parallelised
static int generate_dabits(int batch_bytes, uint8_t *B1, uint32_t *A1){
    int batch_size = batch_bytes * 8;
    
	//s1 chooses n random bits B1
    randombytes_buf(B1, batch_bytes);

	//s1 chooses n random field elements X and sets y1 = -x mod p for each one
    uint32_t *X = malloc(batch_size * sizeof(uint32_t));
    if(!X){
        printf("could not allocate X\n");
        return -1;
    }
    random_vector(X, batch_size, FF_size);

    for(int i = 0; i < batch_size; i++)
        A1[i] = FF_convert(-X[i], FF_size);
    
	//s2 chooses n random bits B2
    //randombytes_buf(B2, batch_bytes);

	//s1 acts as OT sender, sending (x, x + b1), s2 acts as receiver with choice bit b2
    uint32_t *messages1 = X;
    uint32_t *messages2 = malloc(batch_size * sizeof(uint32_t));
    if(!messages2){
        printf("could not allocate message2\n");
        return -1;
    }
    int byte = 0, bit = 0;
    for(int i = 0; i < batch_size; i++){
        if(bit > 7){
            bit = 0;
            byte++;
        }
        messages2[i] = FF_convert(X[i] + (B1[byte] >> bit++ & 1), FF_size);
    }
    OTeSend32(messages1, messages2, batch_size);
    free(messages1);
    free(messages2);
	//both servers compute a_i = b_i - 2*y_i and output values
    byte = 0, bit = 0;
    for(int i = 0; i < batch_size; i++){
        if(bit > 7){
            bit = 0;
            byte++;
        }
        A1[i] = FF_convert((B1[byte] >> bit++ & 1) - (2 * A1[i]), FF_size);
    }
    if(verbose)
        printf("finished generating dabits\n");
    return 0;
}

// pre-compute a batch of beaver triples in parallel
static int generate_beaver_triples(int batch_bytes, uint8_t (*T1)[batch_bytes]){
    int batch_size = batch_bytes * 8;
    if(batch_size == 0)
        return 0;
	//server 1 samples 'batch_size' bit doubles (a1, b1) plus 'batch_size' random bits R1 for the OTs
    uint8_t *s1_R = malloc(batch_bytes * sizeof(uint8_t));
    if(!s1_R){
        printf("could not allocate space\n");
        return -1;
    }
    randombytes_buf(s1_R, batch_bytes);
    randombytes_buf(T1[0], 2 * batch_bytes);
    
    //server 2 does the same
    
	//perform 2 OTs
    uint8_t *messages1 = s1_R, *messages2 = malloc(batch_bytes * sizeof(uint8_t));
    uint8_t *choices = T1[1], *output = malloc(batch_bytes * sizeof(uint8_t));

    if(!messages2 || !output){
        printf("could not allocate space for messages2 or output\n");
        return -1;
    }
	for(int i = 0; i < batch_bytes; i++)
		messages2[i] = s1_R[i] ^ T1[0][i];
    
    OTeSend1(messages1, messages2, batch_size);
    OTeRecv1(output, choices, batch_size);
    
    for(int i = 0; i < batch_bytes; i++)
		//server 1 acts as the sender, sending (r1, r1 ^ a1)
		//server 2 selects with b2 to learn x2 = a1b2 ^ r1
		//x2 = oblivious_transfer(s1_R[i], s1_R[i] ^ s1_triples[j], s2_triples[j + 1]);
		//server 2 calculates c2 as follows, according to the standard protocol [2]
		//now reverse roles
		//x1 = oblivious_transfer(s2_R[i], s2_R[i] ^ s2_triples[j], s1_triples[j + 1]);	
		T1[2][i] = output[i] ^ s1_R[i] ^ (T1[0][i] & T1[1][i]);

    free(messages1);
    free(messages2);
    free(output);
    if(verbose) printf("finished generating beaver triples\n");
    return 0;
}

//boolean-to-arithmetic conversion for an array of bits seen in [2], but parallelised
static int b2a_convert(int n_fixed, uint32_t *output1, uint8_t *input1, uint8_t *dab1B, uint32_t *dab1A){
    int nbytes_fixed = tobytes(n_fixed);
	//server 1 calculates intermediate values V1
	uint8_t *V1 = input1, *V2 = NULL, *V = dab1B; //reuse arrays for efficiency

	for(int i = 0; i < nbytes_fixed; i++)
        V1[i] = input1[i] ^ dab1B[i];
	
	//server 2 does likewise
    
	//servers share V in the clear
    uint8_t *recv_arr;
    uint64_t count;
    if(send_8(s2_fd, V1, nbytes_fixed) != 0){
        fprintf(stderr, "send V1 to s2 failed\n");
        return -1;
    }
    if(receive_8(s2_fd, &recv_arr, &count) == 0 && count == nbytes_fixed)
        V2 = recv_arr;
    else{
        fprintf(stderr, "receive V2 from s2 failed\n");
        return -1;
    }

	for(int i = 0; i < nbytes_fixed; i++)
		V[i] = V1[i] ^ V2[i];
	//server 1 calculates output x as x = v + [b]^A_1 - 2v[b]^A_1 ([b]^A is the arithmetic share of the dabit)
    int byte = 0, bit = 0;
    bool b;
    for(int i = 0; i < n_fixed; i++){
        if(bit > 7){
            bit = 0;
            byte++;
        }
        b = V[byte] >> bit++ & 1;
        output1[i] = FF_convert(b + dab1A[i] - (2 * b * dab1A[i]), FF_size);
    }
	//server 2 calculates x as x = [b]^A_2 - 2v[b]^A_2
    free(V2);
    return 0;
}

static int verify(uint8_t *arr){
    int no_multis = (L - 1) * m;
    uint8_t T1[3][no_multis];
    if(generate_beaver_triples(no_multis, T1) == -1){
        fprintf(stderr, "error in generate_beaver_triples()\n");
        return -1;
    }
    univ_start = clock();

    printboolvec(arr, 8);
    uint8_t Z1[m], *Z2;
    bool R[line];
    bytestobools(R, arr, line);
    bool t[L];
    for(int j = 0; j < L; j++)
        t[j] = 0;

    for(int i = 0; i < m; i++){
        //fprintf(stderr, "i = %d\n", i);
        int index [1];
        index[0] = 0;
        uint8_t *z = NULL;
        uint8_t alt_D[L][1];
        for(int j = 0; j < L; j++){
            alt_D[j][0] = R[i * L + j];
            //printf("%d\n", alt_D[j][0]);
        }
        if(intersectminus(1, L, L, no_multis, alt_D, &T1[no_multis], &z, index, t) == -1){
            fprintf(stderr, "error in intersectminus()\n");
            return -1;
        }
        Z1[i] = z[0] & 1;
        printf("%d\n", Z1[i]);
        free(z);
    }
    uint8_t *recv_arr;
    uint64_t count, exp_count = m;

    if(receive_8(s2_fd, &recv_arr, &count) == 0 && count == exp_count)
        Z2 = recv_arr;
    else{
        fprintf(stderr, "receive Z2 from s2 failed, no. elements received = %" PRIu64 "\n", count);
        return -1;
    }

    if(send_8(s2_fd, Z1, exp_count) != 0)
        return -1;

    for(int i = 0; i < m; i++)
        //printf("%d\n", Z1[i] ^ Z2[i]);
        if(Z1[i] ^ Z2[i])
            return 0;
    printf("---------------------------------\n");
    univ_end = clock();
    univ_final = (double)(univ_end - univ_start) / CLOCKS_PER_SEC;
    printf("total time = %f\n", univ_final);
    return 1;
}

static int client_update(uint8_t *arr, uint64_t count){
    int linebytes = tobytes(line);
    if(count == linebytes){
        if(!verify(arr)){
            fprintf(stderr, "cheating client, the vector of all 1s is not allowed\n");
            return -1;
        }
        int nbyte, nbit;
        int byte = 0, bit = 0;
        indextobyteandbit(&nbyte, &nbit, n++);
        int oldnbyte = nbytes;
        nbytes = tobytes(n);
        if(nbytes > oldnbyte){
            D1_cols++;
            D = realloc(D, D1_cols * line);
            if(!D){
                printf("error reallocating D1\n");
                return -1;
            }
        }
        if(n + 1 > FF_size){
            fprintf(stderr, "n bigger than FF_size\n");
            FF_size++;
            return -1;
        }
        for(int i = 0; i < line; i++){
            if(bit > 7){
                bit = 0;
                byte++;
            }
            D1(i, nbyte) |= (arr[byte] >> bit & 1) << nbit;
        }
        printf("record added to database\n");
    }
    else fprintf(stderr, "invalid record bitlength, must be %d bits\n", line);
    return 0;
}

static void* client_query_thread(void *arg){
    int n_fixed = n; //fix n at this point so it doesn't change during computation
    int nbytes_fixed = nbytes;
    query_thread_args *args = arg;
    int client_fd = args->client_fd;
    uint8_t *arr = args->arr;
    uint64_t count = args->count;
    int intersection_indices[m];

    int max_q_len_bytes = 16;
    int max_q_len = max_q_len_bytes * 8;

    if(m > max_q_len){
        fprintf(stderr, "need bigger buffer for m\n");
        return NULL;
    }

    int index_len, query_len;
    if(intersect_version == INTERSECT_MINUS || cout)
        index_len = bchartoindexvec(intersection_indices, arr, max_q_len);
    else index_len = m;
    query_len = index_len * L;

    if(count != 1 + max_q_len_bytes + tobytes(query_len)){
        fprintf(stderr, "message len should be 1 (message type) + 16 (q) + %d (t), actual len = %ld\n", tobytes(query_len), count);
        return NULL;
    }
    bool t[query_len];
    bytestobools(t, &arr[max_q_len_bytes], query_len);

    /*fprintf(stderr, "index_len = %d, query_len = %d\n", index_len, query_len);
    for(int i = 0; i < query_len; i++)
        printf("%d\n", t[i]);
    for(int i = 0; i < index_len; i++)
        printf("%d\n", intersection_indices[i]);*/

    uint8_t *dab1B = malloc(nbytes_fixed * sizeof(uint8_t));
    uint32_t *dab1A = malloc(8 * nbytes_fixed * sizeof(uint32_t));
    if(!dab1B || !dab1A){
        printf("error allocating dabits\n");
        return NULL;
    }

    if(generate_dabits(nbytes_fixed, dab1B, dab1A)){
        printf("failed to generate dabits\n");
        return NULL;
    }

    uint8_t *Z1 = NULL;
    if(cout){
        int j = query_len, depth = 0;
        int noOTs_j = 0;
        int js[32], js_acc[32];
        js[0] = j;
        js_acc[0] = 0;

        while(j > rsize){
            if(depth > 32){
                printf("need bigger js array\n");
                return NULL;
            }
            noOTs_j += j;
            j = (int)ceil(log2(j)) + 1;
            depth++;
            js[depth] = j;
            js_acc[depth] = noOTs_j;
        }

        expon = (int)pow(2, rsize) - 2;
        if(light){
            if(!benchmarking){
                uint8_t (*R)[nbytes_fixed] = malloc(noOTs_j * nbytes_fixed * sizeof(uint8_t));
                uint32_t (*A)[nbytes_fixed * 8] = malloc(noOTs_j * (nbytes_fixed * 8) * sizeof(uint32_t));
                if(!R || !A){
                    fprintf(stderr, "could not allocate R or A\n");
                    return NULL;
                }
                int no_multis_bytes = nbytes_fixed * (rsize - 1);
                uint8_t (*T1)[no_multis_bytes] = malloc(3 * no_multis_bytes * sizeof(uint8_t));
                if(!T1){
                    fprintf(stderr, "could not allocate T1\n");
                    return NULL;
                }
                if(generate_beaver_triples(no_multis_bytes, T1) == -1){
                    fprintf(stderr, "error in generate_beaver_triples()\n");
                    return NULL;
                }
                if(couteauHybridPrep(nbytes_fixed, depth, R, A, js, js_acc) == -1){
                    fprintf(stderr, "error in couteauPrep()\n");
                    return NULL;
                }
                if(couteauHybridET(n_fixed, depth, &Z1, R, A, no_multis_bytes, T1, intersection_indices, t, js, js_acc) == -1){
                    fprintf(stderr, "error in couteauHybridET()\n");
                    return NULL;
                }
                free(R);
                free(A);
                free(T1);
            }
            else{/*
                if(benchmarktype == 0)
                    return cout_light_offline_tests(depth, query_len, noOTs_j, js);
                else return cout_light_online_tests(depth, query_len, V1, V2, noOTs_j, js);*/
            }
        }
        else{   //coutfull
            if(!benchmarking){
                uint8_t (*R)[nbytes_fixed] = malloc(noOTs_j * nbytes_fixed * sizeof(uint8_t));
                uint32_t (*A)[nbytes_fixed * 8] = malloc(noOTs_j * (8 * nbytes_fixed) * sizeof(uint32_t));
                if(!R || !A){
                    fprintf(stderr, "could not allocate R or A\n");
                    return NULL;
                }
                uint8_t (*r)[nbytes_fixed] = malloc(expon * nbytes_fixed * sizeof(uint8_t)),
                (*a)[nbytes_fixed] = malloc(expon * nbytes_fixed * sizeof(uint8_t));
                if(!r || !a){
                    fprintf(stderr, "could not allocate r or a\n");
                    return NULL;
                }
                double start_time = 0, end_time = 0, final_time;
                start_time = clock();
                if(couteauPrep(nbytes_fixed, depth, R, A, r, a, js, js_acc) == -1){
                    fprintf(stderr, "error in couteauPrep()\n");
                    return NULL;
                }
                end_time = clock();

                if(couteauET(n_fixed, depth, &Z1, R, A, r, a, intersection_indices, t, js, js_acc) == -1){
                    fprintf(stderr, "error in couteauET()\n");
                    return NULL;
                }
                final_time = (double)(end_time - start_time) / CLOCKS_PER_SEC;
                //final_time += artificial_delay;
                printf("%.2f\n", final_time);
                free(r);
                free(a);
                free(R);
                free(A);
            }
            else{
                /*if(benchmarktype == 0)
                    return cout_full_offline_tests(depth, query_len, noOTs_j, js);
                else return cout_full_online_tests(depth, query_len, V1, V2, noOTs_j, js);*/
            }
        }
    }
    else{   //intersect
        if(!benchmarking){
            int no_multis_bytes = tobytes(n_fixed) * (query_len - 1);
            uint8_t (*T1)[no_multis_bytes] = malloc(3 * no_multis_bytes * sizeof(uint8_t));
            if(!T1){
                fprintf(stderr, "error allocating T1\n");
                return NULL;
            }
            double start_time = 0, end_time = 0, final_time;
            start_time = clock();
            if(generate_beaver_triples(no_multis_bytes, T1) == -1){
                fprintf(stderr, "error in generate_beaver_triples()\n");
                return NULL;
            }
            end_time = clock();
            if(intersect_version == INTERSECT_MINUS){
                if(intersectminus(n_fixed, query_len, L, no_multis_bytes, NULL, T1, &Z1, intersection_indices, t) == -1){
                    fprintf(stderr, "error in intersectminus()\n");
                    return NULL;
                }
            }
            else{
                bool q[m];
                bytestobools(q, arr, m);
                if(intersectfull(n_fixed, no_multis_bytes, T1, &Z1, q, t) == -1){
                    fprintf(stderr, "error in intersectfull()\n");
                    return NULL;
                }
            }
            final_time = (double)(end_time - start_time) / CLOCKS_PER_SEC;
            //final_time += artificial_delay;
            //printf("%.2f\n", final_time);
            free(T1);
        }
        else{/*
            if(benchmarktype == 0)
                return intersect_offline_tests(query_len);
            else return intersect_online_tests(query_len, V1, V2, Z1, Z2);*/
        }
    }
    //printboolvec(Z1, n_fixed);

    uint32_t *Z1_arith = malloc(n_fixed * sizeof(uint32_t));//arithmetic shares of the intersection values, Z1 and Z2
    if(!Z1_arith){
        fprintf(stderr, "could not allocate Z1_arith\n");
        return NULL;
    }

	b2a_convert(n_fixed, Z1_arith, Z1, dab1B, dab1A);
    free(Z1);
    free(dab1B);
    free(dab1A);

	uint32_t s1_total = aggregate_1D(Z1_arith, FF_size, n_fixed);
    printf("s1_total = %d\n", s1_total);
    free(Z1_arith);

    int response_len = 3 * sizeof(uint32_t);
    uint8_t *response = malloc(response_len);
    //response[0] = gc_threshold_check(1, s1_total, FF_size, THRESHOLD, NULL, GCPORT);
    encode_uint32_be(&response[0], s1_total);
    encode_uint32_be(&response[4], FF_size);
    encode_uint32_be(&response[8], THRESHOLD);

    //printf("%d\n", response[0]);

    free(args->arr - 1);
    free(args);

    query_thread_result *result = malloc(sizeof(query_thread_result));
    result->client_fd = client_fd;
    result->response = response;
    result->response_len = response_len;
    // Post result to event loop
    pthread_mutex_lock(&result_queue_mutex);
    enqueue_result(&result_queue, result);
    pthread_mutex_unlock(&result_queue_mutex);

    uint64_t val = 1;
    eventfd_write(exchange_eventfd, val);

    return NULL;
}


static void client_query(connection_t *c, uint8_t *arr, uint64_t count){

    printf("starting client_query\n");
    query_thread_args *args = malloc(sizeof(query_thread_args));
    args->client_fd = c->fd;
    args->arr = arr;
    args->count = count;

    pthread_t t;
    pthread_create(&t, NULL, client_query_thread, args);
    pthread_detach(t);
}


/* -------------------------------------------------------------------------
 * I/O handlers
 * -------------------------------------------------------------------------
 *
 */

static int connection_enqueue(connection_t *c, const uint8_t *data, size_t len){
    write_chunk_t *chunk = malloc(sizeof(write_chunk_t));
    if (!chunk) return -1;
    chunk->buf  = malloc(len);
    if (!chunk->buf) { free(chunk); return -1; }
    memcpy(chunk->buf, data, len);
    chunk->len  = len;
    chunk->off  = 0;
    chunk->next = NULL;

    if (c->write_tail) {
        c->write_tail->next = chunk;
        c->write_tail       = chunk;
    } else {
        // List was empty
        c->write_head = chunk;
        c->write_tail = chunk;
    }
    return 0;
}

// Returns 0 if a complete message is ready, 1 if still accumulating, -1 on error.
static int feed_parser(parser_t *p, const uint8_t *data, size_t len,
                       uint8_t **out_arr, uint64_t *out_count){
    while (len > 0) {
        if (p->state == PARSE_READING_HEADER) {
            size_t need = sizeof(p->header_buf) - p->header_got;
            size_t take = len < need? len: need;
            memcpy(p->header_buf + p->header_got, data, take);
            p->header_got += take;
            data          += take;
            len           -= take;

            if (p->header_got < sizeof(p->header_buf)){
                printf("still waiting for rest of header\n");
                return 1;
            }

            // Header complete — decode and validate
            p->count = decode_uint64_be(p->header_buf);
            if (p->count == 0 || p->count > MAX_ARRAY_ELEMENTS)
                return -1;
            //printf("count = %ld\n", p->count);
            p->payload = malloc(p->count);
            if (!p->payload) return -1;
            p->payload_got = 0;
            p->state       = PARSE_READING_PAYLOAD;
        }

        if (p->state == PARSE_READING_PAYLOAD) {
            size_t need = p->count - p->payload_got;
            size_t take = len < need? len: need;
            memcpy(p->payload + p->payload_got, data, take);
            p->payload_got += take;
            data           += take;
            len            -= take;

            if (p->payload_got < p->count){
                printf("still waiting for rest of payload\n");
                return 1;
            }

            // Message complete — hand off to caller
            *out_arr   = p->payload;
            *out_count = p->count;

            // Reset for next message
            p->payload     = NULL;
            p->payload_got = 0;
            p->header_got  = 0;
            p->state       = PARSE_READING_HEADER;
            return 0;
        }
    }
    return 1;
}

static void handle_write(connection_t *c){
    while (c->write_head) {
        write_chunk_t *chunk = c->write_head;

        while (chunk->off < chunk->len){
            ssize_t en = send(c->fd,
                             chunk->buf + chunk->off,
                             chunk->len - chunk->off, 0);
            if (en > 0) { chunk->off += (size_t)en; continue; }
            if (errno == EAGAIN || errno == EWOULDBLOCK) return; // wait for next EPOLLOUT
            connection_close(c->fd);
            return;
        }

        // Chunk fully sent — pop it from the list
        c->write_head = chunk->next;
        if (!c->write_head)
            c->write_tail = NULL;   // list now empty
        free(chunk->buf);
        free(chunk);
    }

    // All chunks flushed — disable EPOLLOUT
    epoll_mod(c->fd, EPOLLIN | EPOLLRDHUP | EPOLLET);
}

static void handle_exchange_complete(){
    uint64_t val;
    eventfd_read(exchange_eventfd, &val);

    pthread_mutex_lock(&result_queue_mutex);
    query_thread_result *result = dequeue_result(&result_queue);
    pthread_mutex_unlock(&result_queue_mutex);

    connection_t *c = &conn_table[result->client_fd];
    connection_enqueue(c, result->response, result->response_len);
    handle_write(c);

    free(result->response);
    free(result);
}

static void handle_message(connection_t *c, uint8_t *arr, uint64_t count){
    printf("handling message\n");
    if(count < 2){
        fprintf(stderr, "not enough elements\n");
        return;
    }
    uint8_t mtype = arr[0];
    if(mtype == 0){
        client_update(&arr[1], count - 1);
        free(arr);
    }
    else if(mtype == 1) client_query(c, &arr[1], count);
    else{
        fprintf(stderr, "message type must be 0 (update) or 1 (query)\n");
        free(arr);
    }
}

static void handle_read(connection_t *c){
    uint8_t buf[RECV_BUF_SIZE];
    while(true){
        ssize_t en = recv(c->fd, buf, sizeof(buf), 0);
        if(en > 0){
            uint8_t *arr = NULL;
            uint64_t count = 0;
            int rc = feed_parser(&c->parser, buf, (size_t)en, &arr, &count);
            if(rc == -1){
                fprintf(stderr, "fd=%d parse error\n", c->fd);
                connection_close(c->fd);
                return;
            }
            if(rc == 0){
                // Complete message — equivalent to recv_uint8_array() success
                handle_message(c, arr, count);
            }
            continue;
        }
        if(en == 0){ connection_close(c->fd); return; }
        if(errno == EAGAIN || errno == EWOULDBLOCK) break;
        perror("recv");
        connection_close(c->fd);
        return;
    }
}


static void connection_accept(int listen_fd){
    /*
     * Edge-triggered epoll: we MUST drain all pending accepts in a loop,
     * otherwise we'll miss connections until the next event.
     */
    while(true){
        struct sockaddr_in peer;
        socklen_t peer_len = sizeof(peer);

        int client_fd = accept4(listen_fd, (struct sockaddr *)&peer,
                                &peer_len, SOCK_NONBLOCK | SOCK_CLOEXEC);
        if (client_fd == -1) {
            if (errno == EAGAIN || errno == EWOULDBLOCK)
                break;          /* No more pending connections. */
            perror("accept4");
            break;
        }

        if (client_fd >= MAX_CONNECTIONS) {
            fprintf(stderr, "fd %d exceeds MAX_CONNECTIONS — dropping\n",
                    client_fd);
            close(client_fd);
            continue;
        }

        /* Enable TCP_NODELAY for latency-sensitive traffic (optional). */
        int opt = 1;
        setsockopt(client_fd, IPPROTO_TCP, TCP_NODELAY, &opt, sizeof(opt));

        connection_t *c = &conn_table[client_fd];
        c->fd    = client_fd;
        c->conn_state = CONN_ACTIVE;

        /*
         * EPOLLET  — edge-triggered (fire once per state change)
         * EPOLLIN  — notify when data arrives
         * EPOLLOUT — notify when socket is writable (enable when you have
         *            buffered data to send; disable otherwise to avoid
         *            busy-looping)
         * EPOLLRDHUP — peer closed the write half of the connection
         */
        if (epoll_add(client_fd, EPOLLIN | EPOLLRDHUP | EPOLLET) == -1) {
            perror("epoll_add");
            connection_close(client_fd);
            continue;
        }
        active_count++;
        char addr_str[INET_ADDRSTRLEN];
        inet_ntop(AF_INET, &peer.sin_addr, addr_str, sizeof(addr_str));
        printf("New connection: fd=%d from %s:%d\n",
               client_fd, addr_str, ntohs(peer.sin_port));
        // client_hello
        uint8_t helloBuf[2];
        if(m > 255)
            printf("warning: m too large to fit into uint8_t\n");
        if(L > 255)
            printf("warning: L too large to fit into uint8_t\n");
        helloBuf[0] = m;
        helloBuf[1] = L;
        connection_enqueue(c, helloBuf, 2);
        handle_write(c);
    }
}



/* -------------------------------------------------------------------------
 * Signal handler
 * ---------------------------------------------------------------------- */


static void begin_graceful_shutdown(int listen_fd){
    printf("Graceful shutdown initiated — draining %d connections "
           "(timeout %ds)\n", active_count, GRACEFUL_TIMEOUT_SECS);

    // Stop accepting new connections
    epoll_ctl(epoll_fd, EPOLL_CTL_DEL, listen_fd, NULL);
    close(listen_fd);

    // Signal EOF to every connected client
    for (int fd = 0; fd < MAX_CONNECTIONS; fd++) {
        if (conn_table[fd].conn_state == CONN_ACTIVE) {
            conn_table[fd].conn_state = CONN_CLOSING;
            shutdown(fd, SHUT_WR);  // sends FIN; we can still recv()
        }
    }
}

static void event_loop(int listen_fd){
    struct epoll_event events[MAX_EVENTS];
    int listen_fd_open = 1;

    while (running) {
        // Handle shutdown request
        if (shutdown_requested && listen_fd_open) {
            begin_graceful_shutdown(listen_fd);
            listen_fd_open = 0;
        }

        // If all connections drained, we're done
        if (shutdown_requested && active_count == 0)
            break;

        // Calculate epoll timeout
        int timeout_ms = -1;  // block indefinitely by default
        if (shutdown_requested) {
            int secs_left = (int)(shutdown_deadline - time(NULL));
            if (secs_left <= 0) {
                printf("Timeout expired — force-closing %d connections\n",
                       active_count);
                break;
            }
            timeout_ms = secs_left * 1000;
        }

        int rc = epoll_wait(epoll_fd, events, MAX_EVENTS, timeout_ms);
        if (rc == -1) {
            if (errno == EINTR) continue;
            perror("epoll_wait");
            break;
        }

        for (int i = 0; i < rc; i++) {
            int fd = events[i].data.fd;
            uint32_t ev = events[i].events;

            if (fd == listen_fd) { connection_accept(listen_fd); continue; }
            if (fd == exchange_eventfd) { handle_exchange_complete();   continue; }
            if (ev & (EPOLLERR | EPOLLHUP))  { connection_close(fd); continue; }

            connection_t *c = &conn_table[fd];
            if (c->conn_state == CONN_FREE) continue;

            if (ev & EPOLLRDHUP) { connection_close(fd); continue; }
            if (ev & EPOLLIN)    handle_read(c);
            if ((ev & EPOLLOUT) && c->conn_state != CONN_FREE) handle_write(c);
        }
    }
}

//server 1
int main(int argc, char* argv[]){
	if(sodium_init() < 0){
		printf("Error initialising sodium library\n");
                return 1;
	}
    //parse system arguments with modest error checking
	if(argc == 5 || argc == 6){
		bool failure = false;
		// atoi function only suitable in trusted environment
		int n_test = atoi(argv[1]);
		int m_test = atoi(argv[2]);
		int L_test = atoi(argv[3]);
        int type_test = atoi(argv[4]);

		if(n_test < 1 || n_test > 10000000){
			printf("n (first argument) should be between 1 and 10000000\n");
			failure = true;
		}
		if(m_test < 1 || m_test > 100){
			printf("m (second argument) should be between 1 and 100\n");
			failure = true;
		}
        if(L_test < 1 || L_test > 32){
			printf("L (third argument) should be between 1 and 32\n");
			failure = true;
		}
        if(type_test < 0 || type_test > 2){
            printf("algorithm type should be 0 (intersect), 1 (hybrid) or 2 (cout)\n");
            failure = true;
        }
		if(argc == 6){
			if(strcmp("v", argv[5]) == 0)
				verbose = true;
			else{
				printf("Fifth argument should be \"v\" for verbose or nothing\n");
				failure = true;
			}
		}

		if(failure){
			printf("failure\n");
			return 1;
		}
		n = n_test;
		m = m_test;
		L = L_test;
        cout = type_test > 0? true: false;  //0 = intersect, 1 = coutfull, 2 = coutlite
        light = type_test == 2? true: false;
        line = m * L;
	}	
	else{
		printf("Use 3 args for n, m and L, and optionally \"v\" for verbose\n");
		return 1;
	}
    if(s2_connect() == -1)
        return -1;
    //send algorithm parameters to s2
    if(s2_hello() == -1)
        return -1;
    nbytes = tobytes(n);
    D1_cols = nbytes;
    D = malloc(D1_cols * line);
    if(!D){
        printf("could not allocate D1\n");
        return -1;
    }
    memset(D, 0, D1_cols * line);

	generate_records();

    if(verbose) printf("FF_size = %d\n", FF_size);
	if(verbose) if(print_records() == -1) return -1;

    signal(SIGINT,  on_signal);
    signal(SIGTERM, on_signal);
    signal(SIGPIPE, SIG_IGN);   /* Ignore broken-pipe; check write() return */

    memset(conn_table, 0, sizeof(conn_table));

    epoll_fd = epoll_create1(EPOLL_CLOEXEC);
    if(epoll_fd == -1) { perror("epoll_create1"); return EXIT_FAILURE; }

    int listen_fd = create_listen_socket(CPORT);
    if(listen_fd == -1) return EXIT_FAILURE;

    if(epoll_add(listen_fd, EPOLLIN | EPOLLET) == -1){
        perror("epoll_add listen_fd"); return EXIT_FAILURE;
    }

    exchange_eventfd = eventfd(0, EFD_NONBLOCK | EFD_CLOEXEC);
    if(exchange_eventfd == -1) { perror("eventfd"); return EXIT_FAILURE; }

    if(epoll_add(exchange_eventfd, EPOLLIN | EPOLLET) == -1) {
        perror("epoll_add eventfd"); return EXIT_FAILURE;
    }
    event_loop(listen_fd);

    close(s2_fd);
    close(self_fd);
    close(epoll_fd);

    free(D);

    printf("Server shut down cleanly\n");
    return EXIT_SUCCESS;
}


